ARG NODE_VERSION=16

FROM node:${NODE_VERSION}
RUN apt update

USER node
WORKDIR /home/node/app

# copy files from dist
COPY --chown=node dist ./dist
RUN npm pack ./dist
     
# copy package.json and package-lock.json
COPY --chown=node example/package.json ./example/
RUN cd example && npm install
RUN cd example && npm install ../react-firebaseui-6.0.0.tgz

COPY --chown=node example ./example
# build example
RUN cd example && npm run build

# start the static server
EXPOSE 8000
CMD [ "python3", "-m", "http.server", "--directory", "example/public", "8000" ]
